### ISSUE TITLE
GitHub Actions Secrets are Uppercased

### ISSUE THREAD

**Issue by jamesward** [vanniktech/gradle-maven-publish-plugin#863]
GitHub Actions uppercases secret keys. This makes it a bit awkward to set keys like:
```
ORG_GRADLE_PROJECT_mavenCentralUsername
```

Can the internal logic for all env vars support uppercase variants as well?  Also it'd be nice if all uppercase was the default.

**Comment by kibotu** [comment]
true, I kind of have to map them in the workflow due to this, e.g. 
https://github.com/kibotu/AndroidResourceExtensions/blob/master/.github/workflows/android.yml#L32-L37

```
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
 ```
 
 not sure if there is an easier way to handle this
