### ISSUE TITLE
Could not read PGP secret key

### ISSUE THREAD

**Issue by Loop312** [vanniktech/gradle-maven-publish-plugin#900]
Hi, I decided to learn how to publish a compose multiplatform library, I followed the instructions shown on the template for it in the readme https://kmp.jetbrains.com/#templateGallery (the Multiplatform library) and I've encountered the following issue:

Execution failed for task ':keyhandler:signAndroidReleasePublication'.
> Could not read PGP secret key

or

Execution failed for task ':keyhandler:signDesktopPublication'.
> Could not read PGP secret key

depending on the formatting I put in for the "GPG_KEY_CONTENTS"

as for some of the things i changed up during the process of making the library (off the top of my head):

- I transfered the inner build.gradle.kts code from https://kmp.jetbrains.com/#newProject if you select everything but server
- commented the original inner build.gradle.kts (the section that sets up the project structure and compilation stuff)
- added in the wasm folder and any other i thought were missing
- kept the linux and other "useless" folders that came with the project structure
- used gpg4win which gave me kleopatra as my key manager

I also tried creating a new key and trying different configurations with the "GPG_KEY_CONTENTS" but with the same results

here's the repo if it helps pinpoint the issue: https://github.com/Loop312/compose-keyhandler

I also apologize if this is the wrong place to ask, we can continue somewhere else if it's not

**Comment by shadmanadman** [comment]
Hello. I had the same error. Here is what I did to fix it:

- First, you need to check the content of the `gpg` file that you created using `cat <YOUR GPG FILE>`
The content should be an `ASCII` key. If it's not, then you need to regenerate a new one using:
`gpg --armor --export-secret-keys  _YOUR_KEY_HERE_ > key.gpg`

- In my case In order to read the `local.properties` variables I had to load the file:
```
val keystorePropertiesFile = rootProject.file("local.properties")

val keystoreProperties = Properties()

keystoreProperties.load(FileInputStream(keystorePropertiesFile))
```

Then I could read the variables:
```
useInMemoryPgpKeys(
        keystoreProperties["signing.keyId"].toString(),
        File(keystoreProperties["signing.secretKeyFile"].toString()).readText(),
        keystoreProperties["signing.password"].toString()
    )
```

I hope it helps someone. Happy Coding

**Comment by brainstorm** [comment]
@shadmanadman How would it work for a non-kotlin (Java) project on GitHub Actions CI? I'm currently facing the same issue with this workflow:

https://github.com/umccr/gatk-bwamem-jni/actions/runs/13646557017/job/38146442330

In my [workflow definition](https://github.com/umccr/gatk-bwamem-jni/blob/563ee501c0000ded74e4e30073a994c0f913a5d3/.github/workflows/build.yml), the GPG secret key are imported successfully from a third party GHA action, but this gradle-maven-publish-plugin does not seem to read the GPG ASCII (armor) key properly?

/cc @andrewpatto @reisingerf

**Comment by shadmanadman** [comment]
@brainstorm Sorry. I did not test this using CI Actions. but maybe after loading your GPG keys, you place them in a temp variable and then assign them manually with `useInMemoryPgpKeys`

**Comment by brainstorm** [comment]
> [@brainstorm](https://github.com/brainstorm) Sorry. I did not test this using CI Actions. but maybe after loading your GPG keys, you place them in a temp variable and then assign them manually with `useInMemoryPgpKeys`

That's precisely the mind-twisting bit: I do have that variable set in `secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY` and the first step in the workflow (nothing to do with the `gradle-maven-publish-plugin`, picks that private key up just fine, with the following output:

```
  gpg: directory '/home/runner/.gnupg' created
  gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
  gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
  gpg: key 05AB94DF3E685B24: public key "UMCCR <roman.valls@umccr.org>" imported
  gpg: key 05AB94DF3E685B24: secret key imported
  gpg: Total number processed: 1
  gpg:               imported: 1
  gpg:       secret keys read: 1
  gpg:   secret keys imported: 1
```

But then, `gradle-maven-publish-plugin` config section on CI fails on **the exact same "in memory key" variable**:

```yaml
      - name: Publish package
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
```
